### ISSUE TITLE
Map Controls Offscreen

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/tally#27]
On Chrome and Safari, at least (on the Mac), the Google map controls appear offscreen.

This may have to do with a deliberate decision to render the map larger than the window, but it does make the map less usable; especially on non-mobile devices.

![ScreenGrab 1](https://user-images.githubusercontent.com/51290189/60580898-df8e4480-9d53-11e9-924e-1c478b8d3a78.png)
![ScreenGrab 2](https://user-images.githubusercontent.com/51290189/60580899-df8e4480-9d53-11e9-9513-d848d1a24c50.png)

**Comment by radius314** [comment]
this has been fixed + deployed
