### ISSUE TITLE
Markers Failing to Redraw properly After Zoom Out

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/tally#28]
My setup: Safari on Catalina, with an external monitor (wide).

See the attached.

Step 1: Bring up the map after it initializes.

Step 2: Click "+" (Zoom In). You can move the map to display North America.

Step 3: Click "-" (Zoom Out).

The markers are kind of a mess. It appears as if the previous markers have been left behind, but I can't really say for sure.
![01-FirstMap](https://user-images.githubusercontent.com/51290189/66879727-78587100-ef8d-11e9-8e77-400d9dc997c9.png)
![02-ZoomedAndPanned](https://user-images.githubusercontent.com/51290189/66879728-78587100-ef8d-11e9-99c1-6c26e43ea288.png)
![03-SloppyMess](https://user-images.githubusercontent.com/51290189/66879729-78587100-ef8d-11e9-9136-68702bd4e65e.png)

**Comment by ChrisMarshallNY** [comment]
NOTE: This does not seem to happen with Chrome.

**Comment by ChrisMarshallNY** [comment]
I have a feeling this might be a floating-point precision issue. If I click out again, it stops. If I click back in, it happens again.

In any case, this is not a showstopper, by any stretch.

**Comment by radius314** [comment]
I am not able to reproduce.

**Comment by ChrisMarshallNY** [comment]
Cool. We'll leave it at "question," or I can close it and reopen if I can figure it out.

I have a new monitor that stretches the GPU of my laptop quite a bit; giving odd behavior from time to time. That might have something to do with it.

I'explore a bit more, and see if I can figure it out, but it's not _au priore_.
